# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scaffold < Formula
  desc "CLI tool that creates folder structures and files based on YAML templates"
  homepage "https://github.com/samssjubair/go-directory-scaffolder"
  version "1.0.8"

  on_macos do
    on_intel do
      url "https://github.com/samssjubair/go-directory-scaffolder/releases/download/v1.0.8/go-directory-scaffolder_Darwin_x86_64.tar.gz"
      sha256 "96b116f3821f15cc9138a340071aaddbdd5045a02088b8a76d5a6fbfc853a3a5"

      def install
        bin.install "scaffold"
        puts "🏗️  Directory Scaffolder installed successfully!"
        puts ""
        puts "📋 List templates:     scaffold --list-templates"
        puts "🚀 Create project:     scaffold --template react-app"
        puts "🔍 Preview changes:    scaffold --dry-run project.yaml"
        puts "📖 Show help:         scaffold --help"
        puts ""
        puts "Happy scaffolding! ✨"
      end
    end
    on_arm do
      url "https://github.com/samssjubair/go-directory-scaffolder/releases/download/v1.0.8/go-directory-scaffolder_Darwin_arm64.tar.gz"
      sha256 "751267b11bae57dcc331f62f4625994a8fe0b9326ee6ca937b44f46514df727d"

      def install
        bin.install "scaffold"
        puts "🏗️  Directory Scaffolder installed successfully!"
        puts ""
        puts "📋 List templates:     scaffold --list-templates"
        puts "🚀 Create project:     scaffold --template react-app"
        puts "🔍 Preview changes:    scaffold --dry-run project.yaml"
        puts "📖 Show help:         scaffold --help"
        puts ""
        puts "Happy scaffolding! ✨"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/samssjubair/go-directory-scaffolder/releases/download/v1.0.8/go-directory-scaffolder_Linux_x86_64.tar.gz"
        sha256 "aa51961ebc80b6df4c86b411d711b212fe6df50e0b59a23ef2f1fbdbb737ae06"

        def install
          bin.install "scaffold"
          puts "🏗️  Directory Scaffolder installed successfully!"
          puts ""
          puts "📋 List templates:     scaffold --list-templates"
          puts "🚀 Create project:     scaffold --template react-app"
          puts "🔍 Preview changes:    scaffold --dry-run project.yaml"
          puts "📖 Show help:         scaffold --help"
          puts ""
          puts "Happy scaffolding! ✨"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/samssjubair/go-directory-scaffolder/releases/download/v1.0.8/go-directory-scaffolder_Linux_arm64.tar.gz"
        sha256 "ae6b33af5d94d959e775788591d5195b8702d7ae93e716671c2d5a2acfa69a12"

        def install
          bin.install "scaffold"
          puts "🏗️  Directory Scaffolder installed successfully!"
          puts ""
          puts "📋 List templates:     scaffold --list-templates"
          puts "🚀 Create project:     scaffold --template react-app"
          puts "🔍 Preview changes:    scaffold --dry-run project.yaml"
          puts "📖 Show help:         scaffold --help"
          puts ""
          puts "Happy scaffolding! ✨"
        end
      end
    end
  end

  test do
    system "#{bin}/scaffold --help"
    system "#{bin}/scaffold --list-templates"
    system "#{bin}/scaffold version"
  end
end
